/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppGradientButton: typeof import('./../components/AppGradientButton.vue')['default']
    CbbInputTest: typeof import('./../components/cbb-input-test.vue')['default']
    CbbTest: typeof import('./../components/cbb-test.vue')['default']
    ChatList: typeof import('./../components/ChatList.vue')['default']
    CommentCard: typeof import('./../components/CommentCard.vue')['default']
    Empty: typeof import('./../components/Empty.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    InputBox: typeof import('./../components/InputBox.vue')['default']
    LoginRequiredPopup: typeof import('./../components/LoginRequiredPopup.vue')['default']
    MyList: typeof import('./../components/MyList.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    PopupBox: typeof import('./../components/PopupBox.vue')['default']
    ReportBox: typeof import('./../components/ReportBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    TextBox: typeof import('./../components/TextBox.vue')['default']
    UploaderBox: typeof import('./../components/UploaderBox.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
